---
- name: Configuration de la VM Web
  hosts: all
  become: yes
  vars:
    html_content: "Deploiement avec Terraform et Ansible"
    web_root: "{{ '/usr/share/nginx/html' if ansible_facts['os_family'] == 'RedHat' else '/var/www/html' }}"

  tasks:
    - name: Installation de Nginx
      package:
        name: nginx
        state: present

    - name: Ensure web root exists
      file:
        path: "{{ web_root }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Creation du fichier index.html
      template:
        src: "{{ playbook_dir }}/../site_index.html.j2"
        dest: "{{ web_root }}/index.html"
        mode: '0644'
      notify: Restart Nginx

    - name: S'assurer que Nginx est demarre et active
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted